#define FILEMON_VERSION_MAJOR 1
#define FILEMON_VERSION_MINOR 1
#define FILEMON_VERSION_PATCH 1

#define FILEMON_VERSION_STR \
    "v" STRINGIFY(FILEMON_VERSION_MAJOR) "." \
    STRINGIFY(FILEMON_VERSION_MINOR) "." \
    STRINGIFY(FILEMON_VERSION_PATCH)

#define STRINGIFY(x) _STRINGIFY(x)
#define _STRINGIFY(x) #x